// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj5f0oEpVOGoTTqegj2fYfEnNrjR4gaUk',
    appId: '1:831623937731:web:8a4034f5ff87799db12c76',
    messagingSenderId: '831623937731',
    projectId: 'flutter-iframe-test-612bb',
    authDomain: 'flutter-iframe-test-612bb.firebaseapp.com',
    storageBucket: 'flutter-iframe-test-612bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAALDmRWu0IDvl_2qeKukDvP4CAIxqWFsk',
    appId: '1:831623937731:android:3bc2c9651794aa61b12c76',
    messagingSenderId: '831623937731',
    projectId: 'flutter-iframe-test-612bb',
    storageBucket: 'flutter-iframe-test-612bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBY57jUYYTj4gevlFohq7_HXRhX8XK_s',
    appId: '1:831623937731:ios:0d54ed87195b86aab12c76',
    messagingSenderId: '831623937731',
    projectId: 'flutter-iframe-test-612bb',
    storageBucket: 'flutter-iframe-test-612bb.appspot.com',
    iosClientId: '831623937731-m978tvf0n1dqeg5aqb7pnoge0ifvloca.apps.googleusercontent.com',
    iosBundleId: 'com.example.iframeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBY57jUYYTj4gevlFohq7_HXRhX8XK_s',
    appId: '1:831623937731:ios:0d54ed87195b86aab12c76',
    messagingSenderId: '831623937731',
    projectId: 'flutter-iframe-test-612bb',
    storageBucket: 'flutter-iframe-test-612bb.appspot.com',
    iosClientId: '831623937731-m978tvf0n1dqeg5aqb7pnoge0ifvloca.apps.googleusercontent.com',
    iosBundleId: 'com.example.iframeTest',
  );
}
